export interface BotMetadata {
    id: string;
    name: string;
    description: string;
    category: string;
    difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
    xmlUrl: string;
    imageUrl?: string;
    tags: string[];
}

export const BOT_LIBRARY_CATEGORIES = {
    ALL: 'All',
    DIGITS: 'Digits',
    RISE_FALL: 'Rise/Fall',
    VOLATILITY: 'Volatility',
    TOUCH: 'Touch',
    FLEX: 'Flex Period',
    AUTO_BOT: 'Auto Bot',
    PREMIUM: 'Premium',
    MARKET_TREND: 'Market Trend',
} as const;

// Complete bot library from Free-Dbots folder
export const BOT_LIBRARY: BotMetadata[] = [
    {
        id: 'digit-over-2',
        name: '1 Tick Digit Over 2',
        description: 'Simple digit over strategy for 1 tick trades',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/1 tick DIgit Over 2.xml',
        tags: ['digit', 'over', '1-tick', 'beginner'],
    },
    {
        id: 'mkz-rf-premium',
        name: 'MKZ RF Premium Bot',
        description: 'Premium Rise/Fall strategy with advanced indicators',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/24-MKZ RF PREMIUM BOT.xml',
        tags: ['rise', 'fall', 'premium', 'indicators'],
    },
    {
        id: 'high-digits-420',
        name: '420 High Digits Bot',
        description: 'High digit trading strategy',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/420-High-Digits.xml.xml',
        tags: ['digit', 'high', 'strategy'],
    },
    {
        id: '7-up-digit',
        name: '7 Up Digit Bot',
        description: 'Digit up trading with 7-based logic',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/7-UP-DIGIT-BOT.XML.xml',
        tags: ['digit', 'up', '7'],
    },
    {
        id: 'absolute-deriv',
        name: 'Absolute Deriv Bot',
        description: 'All-in-one comprehensive trading strategy',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Absolute Deriv Bot.xml',
        tags: ['auto', 'comprehensive', 'deriv'],
    },
    {
        id: 'atrium-binary',
        name: 'Atrium Binary Deriv Bot',
        description: 'Binary trading with atrium methodology',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Atrium Binary Deriv Bot.xml',
        tags: ['binary', 'atrium', 'auto'],
    },
    {
        id: 'beam-up-down',
        name: 'BEAM Up-Down RF Auto Bot',
        description: 'Automated Rise/Fall with BEAM technology',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/BEAM-Up-Down-RF-auto-bot.xml.xml',
        tags: ['rise', 'fall', 'beam', 'auto'],
    },
    {
        id: 'bear-market',
        name: 'Bear Market Auto Trader',
        description: 'Optimized for bear market conditions',
        category: BOT_LIBRARY_CATEGORIES.MARKET_TREND,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/BEAR-MARKET-AUTO-BOT-TRADER.XML',
        tags: ['bear', 'market', 'auto', 'trader'],
    },
    {
        id: 'binary-bot-rf',
        name: 'Binary Bot Premium Rise/Fall',
        description: 'Premium Rise/Fall strategy with high win rate',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/binary-bot Premium Rise_Fall .xml',
        tags: ['rise', 'fall', 'premium'],
    },
    {
        id: 'bonus-bot',
        name: 'Bonus Bot',
        description: 'Bonus-optimized trading strategy',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/Bonus Bot.XML',
        tags: ['bonus', 'simple'],
    },
    {
        id: 'bonus-bot-2',
        name: 'Bonus Bot 2',
        description: 'Enhanced bonus trading strategy',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/Bonus Bot2.xml',
        tags: ['bonus', 'enhanced'],
    },
    {
        id: 'bonus-intel-rf',
        name: 'Bonus Intel RF Auto Bot',
        description: 'Intelligent Rise/Fall with bonus optimization',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Bonus- intel-RF-auto-bot (1).xml',
        tags: ['rise', 'fall', 'bonus', 'intel'],
    },
    {
        id: 'bot-sniper',
        name: 'Bot Sniper',
        description: 'Precision entry sniper bot',
        category: BOT_LIBRARY_CATEGORIES.PREMIUM,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Bot Sniper.xml',
        tags: ['sniper', 'precision', 'premium'],
    },
    {
        id: 'bull-market',
        name: 'Bull Market Auto Trader',
        description: 'Optimized for bull market conditions',
        category: BOT_LIBRARY_CATEGORIES.MARKET_TREND,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/BULL-MARKET-AUTO-BOT TRADER.XML',
        tags: ['bull', 'market', 'auto', 'trader'],
    },
    {
        id: 'bull-power',
        name: 'Bull Power Binary Bot',
        description: 'Bull market optimized trading strategy',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/BULL-POWER-BINARY-BOT V1.1.xml',
        tags: ['bull', 'power', 'auto'],
    },
    {
        id: 'caleb-fx',
        name: 'Caleb FX DBot',
        description: 'Forex-inspired trading strategy',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/CALEB- FX DBOT 1.xml',
        tags: ['fx', 'forex', 'advanced'],
    },
    {
        id: 'defender-digits',
        name: 'Defender Digits Auto Bot',
        description: 'Defensive digit trading with auto features',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Defender_Digits Auto Bot.xml',
        tags: ['digit', 'defender', 'auto'],
    },
    {
        id: 'digit-over-3',
        name: 'Digit Over 3',
        description: 'Digit over strategy targeting digit 3 and above',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/Digit Over 3.xml',
        tags: ['digit', 'over', 'simple'],
    },
    {
        id: 'digit-over-compounder',
        name: 'Digit Over Compounder Strategy',
        description: 'Compounding digit over strategy for progressive growth',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/DIGIT-OVER COMPOUNDER STRATEGY BOT.xml',
        tags: ['digit', 'over', 'compounder', 'growth'],
    },
    {
        id: 'digit-ranger',
        name: 'Digit Ranger Auto Bot',
        description: 'Automated digit trading with dynamic range detection',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Digit-Ranger-Auto-Bot.xml',
        tags: ['digit', 'ranger', 'auto'],
    },
    {
        id: 'dynamic-digits',
        name: 'Dynamic Digits Auto Bot',
        description: 'Advanced digit strategy with dynamic adaptation',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Dynamic_Digits-Auto-Bot.xml',
        tags: ['digit', 'dynamic', 'auto'],
    },
    {
        id: 'entry-touch',
        name: 'Entry Touch B-Bot',
        description: 'Entry point optimization for touch trades',
        category: BOT_LIBRARY_CATEGORIES.TOUCH,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/Entry_Touch_BBot.xml',
        tags: ['touch', 'entry', 'timing'],
    },
    {
        id: 'equalizer-auto',
        name: 'Equalizer Auto Bot v1.1',
        description: 'Balancing strategy with auto features',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Equalizer-Auto-Botv1.1.xml',
        tags: ['equalizer', 'balance', 'auto'],
    },
    {
        id: 'exponential-strategy',
        name: 'Exponential Strategy Bot 2.0',
        description: 'Exponential growth trading strategy',
        category: BOT_LIBRARY_CATEGORIES.PREMIUM,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Exponential Strategy Bot 2.0.xml',
        tags: ['exponential', 'growth', 'premium'],
    },
    {
        id: 'flex-long-short',
        name: 'Flex Period - Long to Shorter',
        description: 'Dynamic period adjustment from long to short timeframes',
        category: BOT_LIBRARY_CATEGORIES.FLEX,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Flex Period Bot - Long to Shorter  - by DailyPro.xml',
        tags: ['flex', 'period', 'dynamic'],
    },
    {
        id: 'flex-short-long-repeat',
        name: 'Flex Period - Short & Long Repeated',
        description: 'Repeated short and long period cycles for optimal timing',
        category: BOT_LIBRARY_CATEGORIES.FLEX,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Flex Period Bot - Short & Long Repeated Turn - by DailyPro.xml',
        tags: ['flex', 'period', 'repeat'],
    },
    {
        id: 'flex-short-long',
        name: 'Flex Period - Short to Longer',
        description: 'Dynamic period adjustment from short to long timeframes',
        category: BOT_LIBRARY_CATEGORIES.FLEX,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Flex Period Bot - Short to Longer - by DailyPro.xml',
        tags: ['flex', 'period', 'dynamic'],
    },
    {
        id: 'free-digit-social',
        name: 'Free Digit Social Bot',
        description: 'Community-driven digit trading strategy',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/Free Digit Socail Bot.xml',
        tags: ['digit', 'social', 'community'],
    },
    {
        id: 'harami-binary',
        name: 'HARAMI Binary Bot',
        description: 'Harami candlestick pattern trading bot',
        category: BOT_LIBRARY_CATEGORIES.MARKET_TREND,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/HARAMI Binary-Bot.xml',
        tags: ['harami', 'candlestick', 'pattern'],
    },
    {
        id: 'high-profit',
        name: 'High Profit Bot',
        description: 'High profit potential trading strategy',
        category: BOT_LIBRARY_CATEGORIES.PREMIUM,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/High Profit Bot.xml',
        tags: ['profit', 'premium', 'high-risk'],
    },
    {
        id: 'higher-lower-trend',
        name: 'Higher-Lower Trend Challenger',
        description: 'Higher/Lower trend-based challenge strategy',
        category: BOT_LIBRARY_CATEGORIES.MARKET_TREND,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Higher-Lower Trend-Challenger BinaryBot .xml',
        tags: ['higher', 'lower', 'trend', 'challenger'],
    },
    {
        id: 'hl-bearking',
        name: 'HL BearKing Premium Bot',
        description: 'Higher/Lower bear market king strategy',
        category: BOT_LIBRARY_CATEGORIES.PREMIUM,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/HL BearKing premium Bot.xml',
        tags: ['hl', 'bear', 'premium'],
    },
    {
        id: 'hl-easy-profit',
        name: 'HL Easy Profit B-Bot 1st Wave',
        description: 'Easy profit Higher/Lower first wave strategy',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/HL EASY PROFIT B-BOT 1ST WAVE  (1).xml',
        tags: ['hl', 'easy', 'profit', 'wave'],
    },
    {
        id: 'hl-hammer',
        name: 'HL Hammer B-Bot 1.0',
        description: 'Higher/Lower hammer strategy',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/HL HAMMER B-BOT 1.0.xml',
        tags: ['hl', 'hammer', 'pattern'],
    },
    {
        id: 'hl-market-maker-bbot',
        name: 'HL Market-Maker 1.0 B-Bot',
        description: 'Market maker strategy for Higher/Lower (Binary)',
        category: BOT_LIBRARY_CATEGORIES.MARKET_TREND,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/HL Market-Maker 1.0 B-Bot.xml',
        tags: ['hl', 'market-maker', 'liquidity'],
    },
    {
        id: 'hl-market-maker-dbot',
        name: 'HL Market-Maker 1.0 Deriv D-Bot',
        description: 'Market maker strategy for Higher/Lower (Deriv)',
        category: BOT_LIBRARY_CATEGORIES.MARKET_TREND,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/HL Market-Maker 1.0 Deriv D-Bot.xml',
        tags: ['hl', 'market-maker', 'deriv'],
    },
    {
        id: 'house-rf',
        name: 'House of Rise/Fall Auto Bots',
        description: 'Comprehensive Rise/Fall automated trading system',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/House of Rise_Fall Auto_Bots.xml',
        tags: ['rise', 'fall', 'auto', 'house'],
    },
    {
        id: 'insync-equals',
        name: 'Insync Equals Binary Bot',
        description: 'Synchronized equals trading strategy',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Insync_Equals BinaryBot.xml',
        tags: ['equals', 'insync', 'sync'],
    },
    {
        id: 'iso-touch',
        name: 'Iso Touch Auto Bot v2.0.1',
        description: 'Isolated touch trading with automation',
        category: BOT_LIBRARY_CATEGORIES.TOUCH,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/iso_Touch AutoBot V2.0.1.xml',
        tags: ['touch', 'iso', 'auto'],
    },
    {
        id: 'i-digit-v2',
        name: 'I Digit v2.0 Update',
        description: 'Updated intelligent digit trading bot',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/I_DIGIT_V2.0_UPDATE.xml',
        tags: ['digit', 'intelligent', 'update'],
    },
    {
        id: 'last-digit-1',
        name: 'Last Digit 1 Strategy Bot',
        description: 'Strategy focused on last digit being 1',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/LastDigit1-Strategy-Bot.xml',
        tags: ['digit', 'last', 'strategy'],
    },
    {
        id: 'leo-even-odd',
        name: 'Leo Even Odd',
        description: 'Even/Odd digit trading strategy',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/Leo_Even_Odd.xml',
        tags: ['digit', 'even', 'odd', 'leo'],
    },
    {
        id: 'low-risk-manager',
        name: 'Low Risk Manager Deriv Bot',
        description: 'Risk-managed trading strategy for Deriv',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/Low Risk Manager Deriv Bot.xml',
        tags: ['risk', 'manager', 'low-risk', 'deriv'],
    },
    {
        id: 'mavic-air-rf',
        name: 'Mavic-Air RF Vix Bot',
        description: 'Rise/Fall volatility index bot',
        category: BOT_LIBRARY_CATEGORIES.VOLATILITY,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Mavic-Air-RF Vix Bot.xml',
        tags: ['rf', 'vix', 'volatility', 'mavic'],
    },
    {
        id: 'mpsu-smart-up-down',
        name: 'MPSU Smart Up-Down Auto Bot',
        description: 'Smart up/down automated trading',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/MPSU-SMART UP-DOWN AUTO-BOT.XML',
        tags: ['up', 'down', 'smart', 'auto'],
    },
    {
        id: 'one-touch-tetris',
        name: 'One Touch Tetris B-Bot',
        description: 'One touch trading with tetris-style logic',
        category: BOT_LIBRARY_CATEGORIES.TOUCH,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/One Touch Tetris B-Bot.xml',
        tags: ['touch', 'tetris', 'logic'],
    },
    {
        id: 'one-touch-stimuli',
        name: 'One Touch Stimuli Bot',
        description: 'One touch trading with stimulus detection',
        category: BOT_LIBRARY_CATEGORIES.TOUCH,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/ONE-TOUCH-STIMULI-BOT.xml',
        tags: ['touch', 'stimuli', 'detection'],
    },
    {
        id: 'optimo-volatility',
        name: 'Optimo Volatility Auto Bot',
        description: 'Optimized volatility trading automation',
        category: BOT_LIBRARY_CATEGORIES.VOLATILITY,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/OPTIMO-VOLATILITY-AUTO-BOT.XML.xml',
        tags: ['volatility', 'optimo', 'auto'],
    },
    {
        id: 'price-rover-rf',
        name: 'Price Rover RF Strategy',
        description: 'Price roving Rise/Fall strategy',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Price_Rover RF Strategy.xml',
        tags: ['rf', 'price', 'rover', 'strategy'],
    },
    {
        id: 'pulse-up-down',
        name: 'Pulse Up-Down Auto Bot',
        description: 'Pulse-based up/down automated trading',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Pulse-up-down-AutoBot.xml',
        tags: ['pulse', 'up', 'down', 'auto'],
    },
    {
        id: 'quad-digit',
        name: 'Quad Digit Bot',
        description: 'Four-digit combination trading strategy',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Quad Digit Bot.xml',
        tags: ['digit', 'quad', 'combo'],
    },
    {
        id: 'quantum-ends-deriv',
        name: 'Quantum Ends In-Out Deriv D-Bot',
        description: 'Quantum ends strategy for Deriv',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/QUANTUM ENDS-IN-OUT DERIV D-BOT  .xml',
        tags: ['quantum', 'ends', 'in-out', 'deriv'],
    },
    {
        id: 'quantum-ends-binary',
        name: 'Quantum Ends In-Out Binary Bot',
        description: 'Quantum ends strategy for Binary',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/QUANTUM ENDS-IN-OUT-BINARY-BOT .xml',
        tags: ['quantum', 'ends', 'in-out', 'binary'],
    },
    {
        id: 'renko-digits',
        name: 'Renko Digits',
        description: 'Renko chart-based digit trading',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Renko-Digits.xml',
        tags: ['renko', 'digit', 'chart'],
    },
    {
        id: 'rf-blackout',
        name: 'RF Black Out 1.0 Deriv DBot',
        description: 'Rise/Fall blackout strategy',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/RF Black_Out 1.0 Deriv DBot.xml',
        tags: ['rf', 'blackout', 'deriv'],
    },
    {
        id: 'rf-contingency',
        name: 'RF Contingency B-Bot 1.0',
        description: 'Rise/Fall contingency plan strategy',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/RF CONTIGENCY B-BOT 1.0.xml',
        tags: ['rf', 'contingency', 'backup'],
    },
    {
        id: 'rf-heist',
        name: 'RF Heist B-Bot',
        description: 'Aggressive Rise/Fall trading bot',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/RF Heist B-Bot.xml',
        tags: ['rf', 'heist', 'aggressive'],
    },
    {
        id: 'rf-array',
        name: 'RF Array Auto Bot',
        description: 'Array-based Rise/Fall automation',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/RF-ARRAY-autobot.xml',
        tags: ['rf', 'array', 'auto'],
    },
    {
        id: 'rf-compressor',
        name: 'RF Compressor Signal Bot v1.0.1',
        description: 'Signal compression Rise/Fall bot',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/RF-Compressor Signal Bot V1.0.1.xml',
        tags: ['rf', 'compressor', 'signal'],
    },
    {
        id: 'rf-flex',
        name: 'RF Flex',
        description: 'Flexible Rise/Fall strategy',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/RF-Flex.xml',
        tags: ['rf', 'flex', 'flexible'],
    },
    {
        id: 'rf-hi-lo',
        name: 'RF Hi-Lo DBot',
        description: 'Rise/Fall high-low strategy',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/Rf-Hi-Lo DBot.xml',
        tags: ['rf', 'hi-lo', 'simple'],
    },
    {
        id: 'rf-marble',
        name: 'RF Marble B-Bot',
        description: 'Marble-based Rise/Fall strategy',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/RF-MARBLE B-BOT.xml',
        tags: ['rf', 'marble', 'strategy'],
    },
    {
        id: 'rf-optic',
        name: 'RF Optic Trend Bot',
        description: 'Rise/Fall bot with trend detection capabilities',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/RF-OPTIC-TRENDBOT.XML.xml',
        tags: ['rf', 'optic', 'trend'],
    },
    {
        id: 'rf-valor',
        name: 'RF Valor Auto Trader Bot',
        description: 'Valor-based Rise/Fall auto trader',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/RF-Valor-AutoTrader_Bot.xml.xml',
        tags: ['rf', 'valor', 'auto', 'trader'],
    },
    {
        id: 'rf-market-monitor',
        name: 'RF Market Monitor',
        description: 'Rise/Fall with market monitoring',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/RF_Market-Monitor.xml',
        tags: ['rf', 'monitor', 'market'],
    },
    {
        id: 'rf-spider-profit',
        name: 'RF Spider Profit',
        description: 'Spider web profit extraction Rise/Fall strategy',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/RF_Spider_Profit.xml',
        tags: ['rf', 'spider', 'profit'],
    },
    {
        id: 'rise-fall-profittargeter',
        name: 'Rise-Fall Profit Targeter',
        description: 'Target-based Rise/Fall profit strategy',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/RISE-FALL-ProfitTargeter.xml',
        tags: ['rf', 'profit', 'target'],
    },
    {
        id: 'roller-deriv',
        name: 'Roller Deriv Bot',
        description: 'Rolling strategy for consistent profits',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Roller Deriv Bot.xml',
        tags: ['roller', 'deriv', 'consistent'],
    },
    {
        id: 'russ-cobetckar',
        name: 'Russ Cobetckar Deriv Bot',
        description: 'Russ Cobetckar signature strategy',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Russ Cobetckar Deriv Bot.xml',
        tags: ['russ', 'cobetckar', 'signature'],
    },
    {
        id: 'sensei-rf',
        name: 'Sensei RF Binary Bot',
        description: 'Master-level Rise/Fall strategy',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/SENSEI-RF-BINARYBOT.xml',
        tags: ['rf', 'sensei', 'master'],
    },
    {
        id: 'shark-digits',
        name: 'Shark Digits',
        description: 'Aggressive shark-style digit trading',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Shark_Digits.xml',
        tags: ['digit', 'shark', 'aggressive'],
    },
    {
        id: 'shash-digits',
        name: 'SHASH Digits v4-20',
        description: 'SHASH digit trading strategy version 4-20',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/SHASH DIGITS V- 4-20.xml',
        tags: ['digit', 'shash', 'strategy'],
    },
    {
        id: 'sonic-digits',
        name: 'Sonic Digits Binary Bot',
        description: 'Fast-paced sonic digit trading',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Sonic Digits BinaryBot.xml',
        tags: ['digit', 'sonic', 'fast'],
    },
    {
        id: 'sputnik-digit-differ',
        name: 'Sputnik Digit Differ Bot',
        description: 'Digit differ strategy with space-age tech',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/SPUTNIK_DIGIT-DIFFER BOT.xml',
        tags: ['digit', 'differ', 'sputnik'],
    },
    {
        id: 'stealth-mode-digit',
        name: 'Stealth Mode Digit Over Auto Bot',
        description: 'Stealth digit over with auto features',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Stealth-Mode-DigitOver-AutoBot.xml',
        tags: ['digit', 'stealth', 'over', 'auto'],
    },
    {
        id: 'stoch-rsi',
        name: 'Stochastic and RSI Bot',
        description: 'Combined Stochastic and RSI indicator bot',
        category: BOT_LIBRARY_CATEGORIES.MARKET_TREND,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Stoch and RSI Bot.xml',
        tags: ['stochastic', 'rsi', 'indicator'],
    },
    {
        id: 'super-digit-differ',
        name: 'Super Digit Differ Bot',
        description: 'Enhanced digit differ trading bot',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Super Digit Differ Bot.xml',
        tags: ['digit', 'differ', 'super'],
    },
    {
        id: 'super-digit-under',
        name: 'Super Digit Under',
        description: 'Powerful under digit trading strategy',
        category: BOT_LIBRARY_CATEGORIES.DIGITS,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Super Digit Under.xml',
        tags: ['digit', 'under', 'super'],
    },
    {
        id: 'tic-tac-rf',
        name: 'Tic-Tac RF v2.0',
        description: 'Tic-tac-toe style Rise/Fall strategy',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/TIC-TAC RF V2.0.xml',
        tags: ['rf', 'tic-tac', 'game'],
    },
    {
        id: 'tick-pip-rf',
        name: 'Tick-Pip RF',
        description: 'Tick and pip-based Rise/Fall trading',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Beginner',
        xmlUrl: '/bots/Free-Dbots/Tick-Pip Rf.xml',
        tags: ['rf', 'tick', 'pip'],
    },
    {
        id: 'tick-ranger-rf',
        name: 'Tick Ranger RF 2nd Edition',
        description: 'Second edition tick ranger Rise/Fall',
        category: BOT_LIBRARY_CATEGORIES.RISE_FALL,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/TICK-RANGER-RF_2ND{edition}.xml.xml',
        tags: ['rf', 'tick', 'ranger', '2nd'],
    },
    {
        id: 'trend-inverter',
        name: 'Trend Inverter Auto Bot',
        description: 'Trend reversal detection and trading',
        category: BOT_LIBRARY_CATEGORIES.MARKET_TREND,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Trend-Inveter-Auto-bot.xml.xml',
        tags: ['trend', 'inverter', 'reversal', 'auto'],
    },
    {
        id: 'unicorn-only-up-down',
        name: 'Unicorn Only Up-Down Binary Bot',
        description: 'Exclusive up/down unicorn strategy',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Unicorn Only Up-Down BinaryBot.xml',
        tags: ['unicorn', 'up', 'down', 'exclusive'],
    },
    {
        id: 'up-down-volt',
        name: 'Up-Down Volt Binary Bot',
        description: 'Voltage-powered up/down trading',
        category: BOT_LIBRARY_CATEGORIES.AUTO_BOT,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Up-Down Volt Binary Bot.xml',
        tags: ['up', 'down', 'volt', 'power'],
    },
    {
        id: 'vix-100-underdog',
        name: 'VIX 100 Under Dog Index Bot',
        description: 'Underdog VIX 100 index trading',
        category: BOT_LIBRARY_CATEGORIES.VOLATILITY,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/VIX 100 UNDER DOG INDEX BOT.xml',
        tags: ['vix', 'volatility', 'underdog', 'index'],
    },
    {
        id: 'vix-lower',
        name: 'Vix Lower Strategy Bot',
        description: 'Lower volatility index strategy',
        category: BOT_LIBRARY_CATEGORIES.VOLATILITY,
        difficulty: 'Intermediate',
        xmlUrl: '/bots/Free-Dbots/Vix-Lower Strategy Bot.xml',
        tags: ['vix', 'volatility', 'lower'],
    },
    {
        id: 'vix-technical',
        name: 'Volatility Index Technical Analysis',
        description: 'VIX 100 with technical analysis indicators',
        category: BOT_LIBRARY_CATEGORIES.VOLATILITY,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/Volatility-Index-Techinical-Analysis-premium-bot.xml',
        tags: ['vix', 'volatility', 'technical', 'premium'],
    },
    {
        id: 'x-formula-vix',
        name: 'X-Formula VIX 100',
        description: 'Secret formula for VIX 100 trading',
        category: BOT_LIBRARY_CATEGORIES.VOLATILITY,
        difficulty: 'Advanced',
        xmlUrl: '/bots/Free-Dbots/X-Formula-Vix-100.xml.xml',
        tags: ['vix', 'volatility', 'formula', 'x'],
    },
];
