export interface ProBot {
    id: string;
    name: string;
    description: string;
    category: string;
    difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
    fileName: string;
    tags: string[];
}

export const BOT_CATEGORIES = {
    ALL: 'All',
    DIGITS: 'Digits',
    RISE_FALL: 'Rise/Fall',
    VOLATILITY: 'Volatility',
    TOUCH: 'Touch',
    FLEX: 'Flex Period',
    PREMIUM: 'Premium',
    AUTO_BOT: 'Auto Bot',
} as const;

export const BOT_DIFFICULTIES = {
    BEGINNER: 'Beginner',
    INTERMEDIATE: 'Intermediate',
    ADVANCED: 'Advanced',
} as const;

//

// Curated bot list from Free-Dbots
export const PRO_BOTS: ProBot[] = [
    {
        id: 'digit-over-2',
        name: '1 Tick Digit Over 2',
        description: 'Simple digit over strategy for 1 tick trades',
        category: BOT_CATEGORIES.DIGITS,
        difficulty: BOT_DIFFICULTIES.BEGINNER,
        fileName: '1 tick DIgit Over 2.xml',
        tags: ['digit', 'over', '1-tick', 'beginner'],
    },
    {
        id: 'digit-over-3',
        name: 'Digit Over 3',
        description: 'Digit over strategy targeting digit 3 and above',
        category: BOT_CATEGORIES.DIGITS,
        difficulty: BOT_DIFFICULTIES.BEGINNER,
        fileName: 'Digit Over 3.xml',
        tags: ['digit', 'over', 'simple'],
    },
    {
        id: 'digit-ranger',
        name: 'Digit Ranger Auto Bot',
        description: 'Automated digit trading with dynamic range detection',
        category: BOT_CATEGORIES.DIGITS,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'Digit-Ranger-Auto-Bot.xml',
        tags: ['digit', 'auto', 'ranger'],
    },
    {
        id: 'dynamic-digits',
        name: 'Dynamic Digits Auto Bot',
        description: 'Advanced digit strategy with dynamic adaptation',
        category: BOT_CATEGORIES.DIGITS,
        difficulty: BOT_DIFFICULTIES.ADVANCED,
        fileName: 'Dynamic_Digits-Auto-Bot.xml',
        tags: ['digit', 'auto', 'dynamic'],
    },
    {
        id: 'super-digit-under',
        name: 'Super Digit Under',
        description: 'Powerful under digit trading strategy',
        category: BOT_CATEGORIES.DIGITS,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'Super Digit Under.xml',
        tags: ['digit', 'under', 'advanced'],
    },
    {
        id: 'rf-premium',
        name: 'MKZ RF Premium Bot',
        description: 'Premium Rise/Fall strategy with advanced indicators',
        category: BOT_CATEGORIES.RISE_FALL,
        difficulty: BOT_DIFFICULTIES.ADVANCED,
        fileName: '24-MKZ RF PREMIUM BOT.xml',
        tags: ['rise', 'fall', 'premium', 'indicators'],
    },
    {
        id: 'binary-bot-rf',
        name: 'Binary Bot Premium Rise/Fall',
        description: 'Premium Rise/Fall strategy with high win rate',
        category: BOT_CATEGORIES.RISE_FALL,
        difficulty: BOT_DIFFICULTIES.ADVANCED,
        fileName: 'binary-bot Premium Rise_Fall .xml',
        tags: ['rise', 'fall', 'premium'],
    },
    {
        id: 'rf-optic',
        name: 'RF Optic Trend Bot',
        description: 'Rise/Fall bot with trend detection capabilities',
        category: BOT_CATEGORIES.RISE_FALL,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'RF-OPTIC-TRENDBOT.XML.xml',
        tags: ['rise', 'fall', 'trend', 'optic'],
    },
    {
        id: 'house-rf',
        name: 'House of Rise/Fall Auto Bot',
        description: 'Comprehensive Rise/Fall automated trading system',
        category: BOT_CATEGORIES.RISE_FALL,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'House of Rise_Fall Auto_Bots.xml',
        tags: ['rise', 'fall', 'auto', 'comprehensive'],
    },
    {
        id: 'rf-heist',
        name: 'RF Heist B-Bot',
        description: 'Aggressive Rise/Fall trading bot',
        category: BOT_CATEGORIES.RISE_FALL,
        difficulty: BOT_DIFFICULTIES.ADVANCED,
        fileName: 'RF Heist B-Bot.xml',
        tags: ['rise', 'fall', 'aggressive'],
    },
    {
        id: 'high-profit',
        name: 'High Profit Bot',
        description: 'High profit potential trading strategy',
        category: BOT_CATEGORIES.PREMIUM,
        difficulty: BOT_DIFFICULTIES.ADVANCED,
        fileName: 'High Profit Bot.xml',
        tags: ['profit', 'premium', 'high-risk'],
    },
    {
        id: 'absolute-deriv',
        name: 'Absolute Deriv Bot',
        description: 'All-in-one comprehensive trading strategy',
        category: BOT_CATEGORIES.AUTO_BOT,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'Absolute Deriv Bot.xml',
        tags: ['auto', 'comprehensive', 'deriv'],
    },
    {
        id: 'bull-power',
        name: 'Bull Power Binary Bot',
        description: 'Bull market optimized trading strategy',
        category: BOT_CATEGORIES.AUTO_BOT,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'BULL-POWER-BINARY-BOT V1.1.xml',
        tags: ['bull', 'market', 'auto'],
    },
    {
        id: 'bear-market',
        name: 'Bear Market Auto Trader',
        description: 'Optimized for bear market conditions',
        category: BOT_CATEGORIES.AUTO_BOT,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'BEAR-MARKET-AUTO-BOT-TRADER.XML',
        tags: ['bear', 'market', 'auto'],
    },
    {
        id: 'one-touch-stimuli',
        name: 'One Touch Stimuli Bot',
        description: 'One touch trading with stimulus detection',
        category: BOT_CATEGORIES.TOUCH,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'ONE-TOUCH-STIMULI-BOT.xml',
        tags: ['touch', 'one-touch', 'stimuli'],
    },
    {
        id: 'entry-touch',
        name: 'Entry Touch B-Bot',
        description: 'Entry point optimization for touch trades',
        category: BOT_CATEGORIES.TOUCH,
        difficulty: BOT_DIFFICULTIES.BEGINNER,
        fileName: 'Entry_Touch_BBot.xml',
        tags: ['touch', 'entry', 'timing'],
    },
    {
        id: 'flex-long-short',
        name: 'Flex Period - Long to Shorter',
        description: 'Dynamic period adjustment from long to short',
        category: BOT_CATEGORIES.FLEX,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'Flex Period Bot - Long to Shorter - by DailyPro.xml',
        tags: ['flex', 'period', 'dynamic', 'dailypro'],
    },
    {
        id: 'flex-short-long',
        name: 'Flex Period - Short to Longer',
        description: 'Dynamic period adjustment from short to long',
        category: BOT_CATEGORIES.FLEX,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'Flex Period Bot - Short to Longer - by DailyPro.xml',
        tags: ['flex', 'period', 'dynamic', 'dailypro'],
    },
    {
        id: 'vix-volatility',
        name: 'Volatility Index Technical Analysis',
        description: 'VIX 100 with technical analysis indicators',
        category: BOT_CATEGORIES.VOLATILITY,
        difficulty: BOT_DIFFICULTIES.ADVANCED,
        fileName: 'Volatility-Index-Techinical-Analysis-premium-bot.xml',
        tags: ['vix', 'volatility', 'technical', 'premium'],
    },
    {
        id: 'roller-deriv',
        name: 'Roller Deriv Bot',
        description: 'Rolling strategy for consistent profits',
        category: BOT_CATEGORIES.AUTO_BOT,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'Roller Deriv Bot.xml',
        tags: ['roller', 'auto', 'consistent'],
    },
    {
        id: 'bot-sniper',
        name: 'Bot Sniper',
        description: 'Precision entry sniper bot',
        category: BOT_CATEGORIES.PREMIUM,
        difficulty: BOT_DIFFICULTIES.ADVANCED,
        fileName: 'Bot Sniper.xml',
        tags: ['sniper', 'precision', 'premium'],
    },
    {
        id: 'bonus-bot',
        name: 'Bonus Bot',
        description: 'Optimized for bonus account trading',
        category: BOT_CATEGORIES.AUTO_BOT,
        difficulty: BOT_DIFFICULTIES.BEGINNER,
        fileName: 'Bonus Bot.XML',
        tags: ['bonus', 'safe', 'beginner'],
    },
    {
        id: 'equalizer-auto',
        name: 'Equalizer Auto Bot',
        description: 'Balanced auto trading with risk management',
        category: BOT_CATEGORIES.AUTO_BOT,
        difficulty: BOT_DIFFICULTIES.INTERMEDIATE,
        fileName: 'Equalizer-Auto-Botv1.1.xml',
        tags: ['equalizer', 'balanced', 'auto'],
    },
    {
        id: 'low-risk-manager',
        name: 'Low Risk Manager Deriv Bot',
        description: 'Conservative strategy with low risk exposure',
        category: BOT_CATEGORIES.AUTO_BOT,
        difficulty: BOT_DIFFICULTIES.BEGINNER,
        fileName: 'Low Risk Manager Deriv Bot.xml',
        tags: ['low-risk', 'safe', 'conservative'],
    },
];
